name: Atualizar JSON Automaticamente

on:
  schedule:
    - cron: '0 11 * * *'    # 08:00 BRT
    - cron: '20 11 * * *'   # 08:20 BRT
    - cron: '40 11 * * *'   # 08:40 BRT
    - cron: '0 12 * * *'    # 09:00 BRT
    - cron: '20 12 * * *'   # 09:20 BRT
  workflow_dispatch:        # Permite execução manual

jobs:
  atualizar-json:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 🔄 Clonar o repositório
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests python-dotenv schedule

      - name: ▶️ Executar script Python
        run: python basedispmovel.py
